"""Durable execution foundation (M1).

Public surface:

- :class:`Controller` and :class:`FlowStatus` — the ADR-0004 lifecycle state
  machine with atomic outbox writes, action journaling and worker leases.
- :func:`forge.durable.gates.record_approval` / ``consume_approval`` — ADR-0009
  human gates.
- :func:`forge.durable.inbox.ingest_event` — idempotent webhook ingestion
  (ADR-0005).
- The six durable tables in :mod:`forge.durable.models`.
"""

from forge.durable.budgets import (
    BUDGET_EXHAUSTED,
    BudgetGuard,
    BudgetLimits,
    Reservation,
    budget_block_reason,
    budget_for_run,
    budget_limits_from_spec,
    close_budget,
    load_budget_guard,
    open_budget,
    open_budget_from_spec,
    reconcile_actual,
    reconcile_harness_receipt,
    reserve,
    resolve_budget_limits,
)
from forge.durable.claims import (
    ExecutionClaim,
    bind_claim,
    current_claim,
)
from forge.durable.controller import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATUSES,
    TRANSITION_EVENT_TYPE,
    ActionLogNotFound,
    Controller,
    ControllerError,
    FlowStatus,
    InvalidActionTransition,
    InvalidTransition,
    RunNotFound,
    StaleClaimError,
    StepRunNotFound,
    as_aware_utc,
)
from forge.durable.gates import (
    ControllerGateError,
    GateAlreadyConsumed,
    GateNotFound,
    consume_approval,
    is_valid,
    record_approval,
)
from forge.durable.identity import factory_branch, plan_digest_of, short_run_id
from forge.durable.inbox import (
    build_source_event_id,
    ingest_event,
    mark_processed,
    mark_rejected,
)
from forge.durable.intents import (
    OPEN_STATES,
    TERMINAL_STATES,
    InvalidIntentTransition,
    ProbeObservation,
    ProbeVerdict,
    classify_probe,
    commit_matches,
    complete_intent,
    due_intents,
    find_open_intent,
    mark_dispatched,
    message_with_marker,
    mint_operation_key,
    op_marker,
    record_intent,
)
from forge.durable.models import (
    FLOW_STATUSES,
    ActionLog,
    BudgetReservation,
    EventInbox,
    FlowRun,
    GateApproval,
    LLMCall,
    Outbox,
    PublicationIntent,
    RunBudget,
    RunSpec,
    StepRun,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "BUDGET_EXHAUSTED",
    "OPEN_STATES",
    "TERMINAL_STATES",
    "ExecutionClaim",
    "FLOW_STATUSES",
    "ActionLog",
    "ActionLogNotFound",
    "BudgetGuard",
    "BudgetLimits",
    "BudgetReservation",
    "Controller",
    "ControllerError",
    "ControllerGateError",
    "EventInbox",
    "FlowRun",
    "FlowStatus",
    "GateAlreadyConsumed",
    "GateApproval",
    "GateNotFound",
    "InvalidActionTransition",
    "InvalidIntentTransition",
    "InvalidTransition",
    "LLMCall",
    "Outbox",
    "ProbeObservation",
    "ProbeVerdict",
    "PublicationIntent",
    "Reservation",
    "RunBudget",
    "RunNotFound",
    "RunSpec",
    "StaleClaimError",
    "TERMINAL_STATUSES",
    "TRANSITION_EVENT_TYPE",
    "StepRun",
    "StepRunNotFound",
    "as_aware_utc",
    "bind_claim",
    "budget_block_reason",
    "budget_for_run",
    "budget_limits_from_spec",
    "build_source_event_id",
    "classify_probe",
    "close_budget",
    "commit_matches",
    "complete_intent",
    "consume_approval",
    "current_claim",
    "due_intents",
    "factory_branch",
    "find_open_intent",
    "ingest_event",
    "is_valid",
    "load_budget_guard",
    "mark_dispatched",
    "mark_processed",
    "mark_rejected",
    "message_with_marker",
    "mint_operation_key",
    "open_budget",
    "open_budget_from_spec",
    "op_marker",
    "plan_digest_of",
    "reconcile_actual",
    "reconcile_harness_receipt",
    "record_approval",
    "record_intent",
    "reserve",
    "resolve_budget_limits",
    "short_run_id",
]
