#!/usr/bin/env python3
"""Render the README version pins and the lane-template pins from archived evidence.

R32-19: the image pins users copy out of the README may only cite artifacts
whose promotion evidence is ARCHIVED — the hand-edited ``ghcr.io/...:tag``
lines were exactly the drift surface the release-evidence discipline
removes. This script reads the latest committed promotion record under
``docs/releases/evidence/v*/promotion.json`` and rewrites the pin blocks in
the target docs; everything it owns sits between the fences::

    <!-- generated by scripts/generate_template_pins.py -- begin -->
    ...
    <!-- generated by scripts/generate_template_pins.py -- end -->

Q35-08: the same record now also renders the LANE PIN inside the shipped
GitHub harness template (and its dogfood mirror) — the promoted version is
the template's DEFAULT lane version and the promoted wheel (when the record
built one) its DEFAULT install artifact, replacing the old hardcoded
``v0.27.0`` git-ref fallback. The lane pin sits between shell-comment fences
(valid inside the workflow's ``run: |`` block)::

    # forge-lane-pin generated by scripts/generate_template_pins.py -- begin
    FORGE_LANE_PROMOTED_VERSION="v0.34.0"
    ...
    # forge-lane-pin generated by scripts/generate_template_pins.py -- end

Pre-release window: when the tree's ``__version__`` is NEWER than the
latest archived record, BOTH the README pins and the lane pin keep stating
the LAST PROMOTED release — an unreleased tree never becomes a lane default
(same window semantics as the README status block).

Idempotent by construction (same facts in, same bytes out). ``--check``
never writes: it exits non-zero when any target file does not match the
generated content — the CI drift guard.

The generated block carries the promotion VERDICT, not just the tag: a
release whose required checks failed is pinned with that fact stated, so a
reader copying the digest knows exactly what qualified it (or did not).

Usage::

    python3 scripts/generate_template_pins.py              # rewrite the blocks
    python3 scripts/generate_template_pins.py --check      # CI drift check
    python3 scripts/generate_template_pins.py --templates  # lane templates only

Stdlib-only (mirrors scripts/canary_smoke.py): no forge import, no network —
the evidence archive is the only input.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

BEGIN = "<!-- generated by scripts/generate_template_pins.py -- begin -->"
END = "<!-- generated by scripts/generate_template_pins.py -- end -->"

#: The lane-pin fences — SHELL comments, because the block lives inside the
#: workflow templates' ``run: |`` script (an HTML comment would execute as
#: a bogus redirection there).
LANE_PIN_BEGIN = "# forge-lane-pin generated by scripts/generate_template_pins.py -- begin"
LANE_PIN_END = "# forge-lane-pin generated by scripts/generate_template_pins.py -- end"

_IMAGE_TAG = "ghcr.io/forcewake/forge"
_RELEASE_ASSET_URL = "https://github.com/forcewake/forge/releases/download/v{version}/{name}"


class PinsError(RuntimeError):
    """The pins cannot be generated from the evidence archive."""


@dataclass(frozen=True)
class _Record:
    """The facts the pins render from (a decoded promotion record)."""

    version: str
    digest: str
    verdict: str
    check_verdicts: tuple[tuple[str, str], ...]  # (name, verdict)
    canary_outcomes: tuple[tuple[str, str], ...]  # (stage, outcome)
    ci_run_id: str | None
    #: Q35-08 lane-artifact identity — the promoted wheel's published URL and
    #: sha256, both empty when the record built no wheel (image-only).
    wheel_url: str = ""
    wheel_sha256: str = ""


def _lane_wheel_identity(document: dict) -> tuple[str, str]:
    """(url, sha256) of the promoted lane wheel; ("", "") when not built.

    Q35-08 additive fields first (``wheel_url`` / ``wheel_sha256`` — what
    the release pipeline records when it builds the wheel set); the legacy
    ``wheel.wheel`` FileIdentity (name + sha256) is the fallback, with the
    URL derived from the canonical release-asset location. A pin renders
    only when BOTH halves resolve — a wheel without a reproducible hash is
    not a pin. Image-only records (v0.33.0/v0.34.0) honestly yield ("", "").
    """
    url = str(document.get("wheel_url") or "")
    sha = str(document.get("wheel_sha256") or "")
    wheel_doc = document.get("wheel")
    wheel_file = wheel_doc.get("wheel") if isinstance(wheel_doc, dict) else None
    name = ""
    if isinstance(wheel_file, dict):
        name = str(wheel_file.get("name") or "")
        if not sha:
            sha = str(wheel_file.get("sha256") or "")
    if sha and not url and name:
        url = _RELEASE_ASSET_URL.format(version=document.get("version"), name=name)
    if not (url and sha):
        return "", ""
    return url, sha


def latest_record(root: Path) -> tuple[_Record, Path]:
    """The promotion record of the highest archived version."""
    base = root / "docs" / "releases" / "evidence"
    if not base.is_dir():
        raise PinsError(f"no release-evidence archive under {base} — run the promotion gate first")
    candidates: list[tuple[tuple[int, ...], Path, dict]] = []
    for path in sorted(base.glob("v*/promotion.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        version = str(document.get("version", ""))
        numbers = tuple(int(p) for p in version.split(".")[:3] if p.isdigit())
        if len(numbers) == 3:
            candidates.append((numbers, path, document))
    if not candidates:
        raise PinsError(f"no readable promotion.json under {base}")
    _, path, document = max(candidates)
    decision = document.get("decision") or {}
    wheel_url, wheel_sha256 = _lane_wheel_identity(document)
    record = _Record(
        version=str(document["version"]),
        digest=str(document["image_digest"]),
        verdict=str(decision.get("verdict", "unknown")),
        check_verdicts=tuple(
            (str(c.get("name")), str(c.get("verdict"))) for c in decision.get("checks", ())
        ),
        canary_outcomes=tuple(
            (str(r.get("stage")), str(r.get("outcome"))) for r in document.get("canary", ())
        ),
        ci_run_id=(str(document["ci_run_id"]) if document.get("ci_run_id") else None),
        wheel_url=wheel_url,
        wheel_sha256=wheel_sha256,
    )
    return record, path


def current_version(root: Path) -> str | None:
    """The version the tree is being released as (``src/forge/__init__.py``).

    Stdlib-only: the ``__version__`` literal is read without importing forge
    (this script runs in CI before install). Trees without the package file
    (test fixtures) return ``None`` — no pending window, pins render the
    archived record verbatim.
    """
    init = root / "src" / "forge" / "__init__.py"
    if not init.is_file():
        return None
    match = re.search(
        r"^__version__\s*=\s*\"([^\"]+)\"", init.read_text(encoding="utf-8"), re.MULTILINE
    )
    return match.group(1) if match else None


def _version_key(version: str) -> tuple[int, ...]:
    return tuple(int(p) for p in version.split(".")[:3] if p.isdigit())


def _verdict_line(record: _Record) -> str:
    """A one-line, honest promotion status derived from the record."""
    if record.verdict == "block":
        bad = [
            name
            for name, verdict in record.check_verdicts
            if verdict in {"fail", "not_executed", "unknown"}
        ]
        bad += [
            f"canary stage {stage}"
            for stage, outcome in record.canary_outcomes
            if outcome == "fail"
        ]
        what = ", ".join(bad) if bad else "no qualifying evidence"
        return f"verdict `blocked` ({what})"
    if record.verdict == "conditional_promote":
        retried = [name for name, verdict in record.check_verdicts if verdict == "conditional_pass"]
        skipped = [stage for stage, outcome in record.canary_outcomes if outcome == "skip"]
        bits = [f"retry-passed: {', '.join(retried)}"] if retried else []
        if skipped:
            bits.append(f"skipped stages: {', '.join(skipped)}")
        detail = "; ".join(bits) if bits else "with recorded conditions"
        return f"verdict `conditional_promote` ({detail})"
    if record.verdict == "promote":
        return "verdict `promote`"
    return f"verdict `{record.verdict}` (unknown — treat as unqualified)"


def render_status_block(record: _Record, evidence_rel: str) -> str:
    """The status-section pin: tag, digest, verdict, evidence pointer."""
    return (
        f"(`{_IMAGE_TAG}:{record.version}` — digest `{record.digest}`, {_verdict_line(record)},\n"
        f"evidence `{evidence_rel}`"
        + (f", qualifying CI run `{record.ci_run_id}`" if record.ci_run_id else "")
        + ")."
    )


def render_lane_pin_block(record: _Record) -> str:
    """The lane pin rendered into the workflow templates (Q35-08).

    The promoted version is the template's DEFAULT lane version; the
    promoted wheel (when the record built one) is the DEFAULT install
    artifact — the authoritative lane distribution. Image-only records
    render empty wheel pins plus the honest note, and the template's
    qualified install route then takes the promoted git TAG (never a
    hardcoded historical fallback). Never takes a pending version: an
    unpromoted tree is not a lane default.
    """
    version_line = f'FORGE_LANE_PROMOTED_VERSION="v{record.version}"'
    if record.wheel_url and record.wheel_sha256:
        wheel_lines = [
            f'FORGE_LANE_PROMOTED_WHEEL_URL="{record.wheel_url}"',
            f'FORGE_LANE_PROMOTED_WHEEL_SHA256="{record.wheel_sha256}"',
        ]
    else:
        wheel_lines = [
            'FORGE_LANE_PROMOTED_WHEEL_URL=""',
            'FORGE_LANE_PROMOTED_WHEEL_SHA256=""',
            f"# the promoted record v{record.version} built no wheel/sdist (image-only",
            "# release) — the qualified install route is the promoted git tag",
        ]
    return "\n".join([version_line, *wheel_lines])


def render_quickstart_block(record: _Record, pending_version: str | None = None) -> str:
    """The quick-start bash block: the tag pin plus the digest-pinned form.

    ``pending_version`` is set only in the pre-release window — the tree's
    ``__version__`` is NEWER than the latest archived record. The quick-start
    then pulls the tag being released (it exists the moment this release's
    attach-tags job runs) while stating plainly that its digest is not yet
    promoted; the archived digest stays the pinned recommendation until the
    new record lands. The status block never renders pending facts — it
    always describes the latest PROMOTED release.
    """
    if pending_version is not None:
        return (
            "```bash\n"
            f"docker run -d --name forge -p 8420:8420 \\\n"
            f"  --env-file .env {_IMAGE_TAG}:{pending_version}\n"
            "# pin the release digest instead of the mutable tag (R30/R32-19):\n"
            f"#   {pending_version}'s digest is recorded in\n"
            f"#   docs/releases/evidence/v{pending_version}/promotion.json once the\n"
            "#   promotion gate qualifies it; until then the digest below (the last\n"
            "#   promoted release) is the pinned recommendation\n"
            f"#   docker run -d --name forge -p 8420:8420 --env-file .env {_IMAGE_TAG}@{record.digest}\n"
            "# or from source:\n"
            "git clone https://github.com/forcewake/forge && cd forge\n"
            "uv sync && set -o pipefail && .venv/bin/python -m pytest -q\n"
            "```"
        )
    digest_ref = f"{_IMAGE_TAG}@{record.digest}"
    return (
        "```bash\n"
        f"docker run -d --name forge -p 8420:8420 \\\n"
        f"  --env-file .env {_IMAGE_TAG}:{record.version}\n"
        "# pin the release digest instead of the mutable tag (R30/R32-19):\n"
        f"#   docker run -d --name forge -p 8420:8420 --env-file .env {digest_ref}\n"
        "# or from source:\n"
        "git clone https://github.com/forcewake/forge && cd forge\n"
        "uv sync && set -o pipefail && .venv/bin/python -m pytest -q\n"
        "```"
    )


# ---------------------------------------------------------------------------
# Targets: where the blocks live, and how to find them the FIRST time (the
# legacy hand-edited pins this script replaces).
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _Spot:
    """One pin location in one file.

    ``legacy`` matches the hand-edited span this script takes over on its
    first run; ``signature`` matches the rendered block's body so the RIGHT
    fenced span is replaced when a file carries several blocks. ``begin`` /
    ``end`` are the fence markers (HTML comments in docs, shell comments
    inside workflow run scripts); ``anchor`` — first-takeover only — matches
    a line the fenced block is inserted BEFORE (used by the lane pin, whose
    legacy shape is not a span to replace but a stale default to retire).
    """

    legacy: re.Pattern[str] | None = None
    signature: re.Pattern[str] = re.compile(r"$^")  # never matches by default
    begin: str = BEGIN
    end: str = END
    anchor: re.Pattern[str] | None = None


_STATUS_LEGACY = re.compile(
    r"\(`" + re.escape(_IMAGE_TAG) + r":[0-9][0-9.abrc]*`\)\.", re.MULTILINE
)
_QUICKSTART_LEGACY = re.compile(
    r"```bash\n[^\n]*\n[^\n]*" + re.escape(_IMAGE_TAG) + r":[0-9][0-9.abrc]*.*?```",
    re.DOTALL,
)
#: First-takeover anchor for the lane pin: the install script's wheel-route
#: preamble line (present in every shipped revision since NEXT-17).
_LANE_PIN_ANCHOR = re.compile(r"(?m)^(?P<indent>[ \t]*)FORGE_WHEEL_URL=.*$")

TARGETS: dict[str, dict[str, _Spot]] = {
    # docs/getting-started/*.md pin no versions today (verified 2026-09-23);
    # add a _Spot per file here when one starts to.
    "README.md": {
        "status": _Spot(legacy=_STATUS_LEGACY, signature=re.compile(r"verdict `")),
        "quickstart": _Spot(legacy=_QUICKSTART_LEGACY, signature=re.compile(r"docker run")),
    },
}

#: Q35-08: the lane pin renders into the SHIPPED GitHub template and the
#: dogfood mirror (this repo runs itself through the lane; its env defaults
#: keep it on the dev source route, so the pin is dormant there until the
#: dev override is switched off).
TEMPLATE_TARGETS: dict[str, dict[str, _Spot]] = {
    relpath: {
        "lane_pin": _Spot(
            signature=re.compile(r"FORGE_LANE_PROMOTED_VERSION="),
            begin=LANE_PIN_BEGIN,
            end=LANE_PIN_END,
            anchor=_LANE_PIN_ANCHOR,
        )
    }
    for relpath in ("ci/templates/forge-harness.github.yml", ".github/workflows/forge-harness.yml")
}


def _fenced_at(begin: str, end: str) -> re.Pattern[str]:
    """A fence matcher that keeps the block's leading indentation (the lane
    pin lives inside an indented ``run: |`` script — the fence must render
    at the SAME indentation it found). Text may follow the end fence on the
    same line (the README status fence carries trailing prose)."""
    return re.compile(
        r"(?m)^(?P<indent>[ \t]*)"
        + re.escape(begin)
        + r"[^\S\n]*\n(?P<body>.*?)\n[ \t]*"
        + re.escape(end),
        re.DOTALL,
    )


def _replace_or_insert(content: str, spot: _Spot, block: str, where: str) -> str:
    pattern = _fenced_at(spot.begin, spot.end)
    for match in pattern.finditer(content):
        if spot.signature.search(match.group("body")):
            indent = match.group("indent")
            body = "\n".join(indent + line if line else line for line in block.split("\n"))
            fenced = f"{indent}{spot.begin}\n{body}\n{indent}{spot.end}"
            return content[: match.start()] + fenced + content[match.end() :]
    if spot.anchor is not None:
        anchor = spot.anchor.search(content)
        if anchor is not None:
            indent = anchor.group("indent")
            body = "\n".join(indent + line if line else line for line in block.split("\n"))
            fenced = f"{indent}{spot.begin}\n{body}\n{indent}{spot.end}\n"
            return content[: anchor.start()] + fenced + content[anchor.start() :]
    if spot.legacy is not None:
        match = spot.legacy.search(content)
        if match is not None:
            fenced = f"{spot.begin}\n{block}\n{spot.end}"
            # Canonical placement: the fence starts at column 0 (a mid-line
            # takeover would leave a fence the next run cannot find).
            prefix = "" if match.start() == 0 or content[match.start() - 1] == "\n" else "\n"
            return content[: match.start()] + prefix + fenced + content[match.end() :]
    raise PinsError(
        f"{where}: no generated pin block and no legacy pin to take over — "
        "add the block manually or fix the anchor"
    )


def generate(
    root: Path,
    files: dict[str, dict[str, _Spot]],
    record: _Record,
    evidence_rel: str,
    pending_version: str | None = None,
) -> dict[str, str]:
    """New content per file (unchanged files map to identical strings)."""
    rendered = {
        "status": lambda: render_status_block(record, evidence_rel),
        "quickstart": lambda: render_quickstart_block(record, pending_version),
        "lane_pin": lambda: render_lane_pin_block(record),
    }
    updated: dict[str, str] = {}
    for relpath, spots in files.items():
        content = (root / relpath).read_text(encoding="utf-8")
        new = content
        for spot_id, spot in spots.items():
            if spot_id not in rendered:
                raise PinsError(f"unknown spot {spot_id!r}")
            new = _replace_or_insert(new, spot, rendered[spot_id](), f"{relpath}:{spot_id}")
        updated[relpath] = new
    return updated


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the target files match the generated content; exit 1 on drift",
    )
    parser.add_argument(
        "--templates",
        action="store_true",
        help="render ONLY the lane-template pins (Q35-08); the default run covers "
        "the README pins and the templates together",
    )
    args = parser.parse_args(argv)

    record, record_path = latest_record(args.root)
    evidence_rel = record_path.relative_to(args.root).as_posix()
    tree_version = current_version(args.root)
    pending_version: str | None = None
    if tree_version and _version_key(tree_version) > _version_key(record.version):
        pending_version = tree_version
    files = TEMPLATE_TARGETS if args.templates else {**TARGETS, **TEMPLATE_TARGETS}
    try:
        updated = generate(args.root, files, record, evidence_rel, pending_version)
    except PinsError as exc:
        print(f"generate-template-pins: REFUSED: {exc}", file=sys.stderr)
        return 2

    drifted = False
    for relpath, new in sorted(updated.items()):
        path = args.root / relpath
        current = path.read_text(encoding="utf-8")
        if current == new:
            print(f"generate-template-pins: {relpath} in sync (v{record.version})")
            continue
        drifted = True
        if args.check:
            print(
                f"generate-template-pins: DRIFT — {relpath} does not match the pins "
                f"generated from {evidence_rel}; run "
                f"`python3 scripts/generate_template_pins.py` and commit",
                file=sys.stderr,
            )
        else:
            path.write_text(new, encoding="utf-8")
            print(f"generate-template-pins: rewrote {relpath} (v{record.version})")

    if args.check and drifted:
        return 1
    window = (
        f" — pre-release window: quick-start pulls v{pending_version} (digest pending promotion)"
        if pending_version
        else ""
    )
    lane = (
        "lane pin: promoted wheel (sha256-verified default)"
        if record.wheel_sha256
        else "lane pin: promoted git tag (image-only record, no wheel built)"
    )
    print(
        f"generate-template-pins: pins render v{record.version} "
        f"({_verdict_line(record)}) from {evidence_rel} — {lane}{window}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
