#!/usr/bin/env python3
"""Render the README version pins from the archived promotion evidence.

R32-19: the image pins users copy out of the README may only cite artifacts
whose promotion evidence is ARCHIVED — the hand-edited ``ghcr.io/...:tag``
lines were exactly the drift surface the release-evidence discipline
removes. This script reads the latest committed promotion record under
``docs/releases/evidence/v*/promotion.json`` and rewrites the pin blocks in
the target docs; everything it owns sits between the fences::

    <!-- generated by scripts/generate_template_pins.py -- begin -->
    ...
    <!-- generated by scripts/generate_template_pins.py -- end -->

Idempotent by construction (same facts in, same bytes out). ``--check``
never writes: it exits non-zero when any target file does not match the
generated content — the CI drift guard.

The generated block carries the promotion VERDICT, not just the tag: a
release whose required checks failed is pinned with that fact stated, so a
reader copying the digest knows exactly what qualified it (or did not).

Usage::

    python3 scripts/generate_template_pins.py            # rewrite the blocks
    python3 scripts/generate_template_pins.py --check    # CI drift check

Stdlib-only (mirrors scripts/canary_smoke.py): no forge import, no network —
the evidence archive is the only input.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

BEGIN = "<!-- generated by scripts/generate_template_pins.py -- begin -->"
END = "<!-- generated by scripts/generate_template_pins.py -- end -->"

_IMAGE_TAG = "ghcr.io/forcewake/forge"


class PinsError(RuntimeError):
    """The pins cannot be generated from the evidence archive."""


@dataclass(frozen=True)
class _Record:
    """The facts the pins render from (a decoded promotion record)."""

    version: str
    digest: str
    verdict: str
    check_verdicts: tuple[tuple[str, str], ...]  # (name, verdict)
    canary_outcomes: tuple[tuple[str, str], ...]  # (stage, outcome)
    ci_run_id: str | None


def latest_record(root: Path) -> tuple[_Record, Path]:
    """The promotion record of the highest archived version."""
    base = root / "docs" / "releases" / "evidence"
    if not base.is_dir():
        raise PinsError(f"no release-evidence archive under {base} — run the promotion gate first")
    candidates: list[tuple[tuple[int, ...], Path, dict]] = []
    for path in sorted(base.glob("v*/promotion.json")):
        document = json.loads(path.read_text(encoding="utf-8"))
        version = str(document.get("version", ""))
        numbers = tuple(int(p) for p in version.split(".")[:3] if p.isdigit())
        if len(numbers) == 3:
            candidates.append((numbers, path, document))
    if not candidates:
        raise PinsError(f"no readable promotion.json under {base}")
    _, path, document = max(candidates)
    decision = document.get("decision") or {}
    record = _Record(
        version=str(document["version"]),
        digest=str(document["image_digest"]),
        verdict=str(decision.get("verdict", "unknown")),
        check_verdicts=tuple(
            (str(c.get("name")), str(c.get("verdict"))) for c in decision.get("checks", ())
        ),
        canary_outcomes=tuple(
            (str(r.get("stage")), str(r.get("outcome"))) for r in document.get("canary", ())
        ),
        ci_run_id=(str(document["ci_run_id"]) if document.get("ci_run_id") else None),
    )
    return record, path


def current_version(root: Path) -> str | None:
    """The version the tree is being released as (``src/forge/__init__.py``).

    Stdlib-only: the ``__version__`` literal is read without importing forge
    (this script runs in CI before install). Trees without the package file
    (test fixtures) return ``None`` — no pending window, pins render the
    archived record verbatim.
    """
    init = root / "src" / "forge" / "__init__.py"
    if not init.is_file():
        return None
    match = re.search(
        r"^__version__\s*=\s*\"([^\"]+)\"", init.read_text(encoding="utf-8"), re.MULTILINE
    )
    return match.group(1) if match else None


def _version_key(version: str) -> tuple[int, ...]:
    return tuple(int(p) for p in version.split(".")[:3] if p.isdigit())


def _verdict_line(record: _Record) -> str:
    """A one-line, honest promotion status derived from the record."""
    if record.verdict == "block":
        bad = [
            name
            for name, verdict in record.check_verdicts
            if verdict in {"fail", "not_executed", "unknown"}
        ]
        bad += [
            f"canary stage {stage}"
            for stage, outcome in record.canary_outcomes
            if outcome == "fail"
        ]
        what = ", ".join(bad) if bad else "no qualifying evidence"
        return f"verdict `blocked` ({what})"
    if record.verdict == "conditional_promote":
        retried = [name for name, verdict in record.check_verdicts if verdict == "conditional_pass"]
        skipped = [stage for stage, outcome in record.canary_outcomes if outcome == "skip"]
        bits = [f"retry-passed: {', '.join(retried)}"] if retried else []
        if skipped:
            bits.append(f"skipped stages: {', '.join(skipped)}")
        detail = "; ".join(bits) if bits else "with recorded conditions"
        return f"verdict `conditional_promote` ({detail})"
    if record.verdict == "promote":
        return "verdict `promote`"
    return f"verdict `{record.verdict}` (unknown — treat as unqualified)"


def render_status_block(record: _Record, evidence_rel: str) -> str:
    """The status-section pin: tag, digest, verdict, evidence pointer."""
    return (
        f"(`{_IMAGE_TAG}:{record.version}` — digest `{record.digest}`, {_verdict_line(record)},\n"
        f"evidence `{evidence_rel}`"
        + (f", qualifying CI run `{record.ci_run_id}`" if record.ci_run_id else "")
        + ")."
    )


def render_quickstart_block(record: _Record, pending_version: str | None = None) -> str:
    """The quick-start bash block: the tag pin plus the digest-pinned form.

    ``pending_version`` is set only in the pre-release window — the tree's
    ``__version__`` is NEWER than the latest archived record. The quick-start
    then pulls the tag being released (it exists the moment this release's
    attach-tags job runs) while stating plainly that its digest is not yet
    promoted; the archived digest stays the pinned recommendation until the
    new record lands. The status block never renders pending facts — it
    always describes the latest PROMOTED release.
    """
    if pending_version is not None:
        return (
            "```bash\n"
            f"docker run -d --name forge -p 8420:8420 \\\n"
            f"  --env-file .env {_IMAGE_TAG}:{pending_version}\n"
            "# pin the release digest instead of the mutable tag (R30/R32-19):\n"
            f"#   {pending_version}'s digest is recorded in\n"
            f"#   docs/releases/evidence/v{pending_version}/promotion.json once the\n"
            "#   promotion gate qualifies it; until then the digest below (the last\n"
            "#   promoted release) is the pinned recommendation\n"
            f"#   docker run -d --name forge -p 8420:8420 --env-file .env {_IMAGE_TAG}@{record.digest}\n"
            "# or from source:\n"
            "git clone https://github.com/forcewake/forge && cd forge\n"
            "uv sync && set -o pipefail && .venv/bin/python -m pytest -q\n"
            "```"
        )
    digest_ref = f"{_IMAGE_TAG}@{record.digest}"
    return (
        "```bash\n"
        f"docker run -d --name forge -p 8420:8420 \\\n"
        f"  --env-file .env {_IMAGE_TAG}:{record.version}\n"
        "# pin the release digest instead of the mutable tag (R30/R32-19):\n"
        f"#   docker run -d --name forge -p 8420:8420 --env-file .env {digest_ref}\n"
        "# or from source:\n"
        "git clone https://github.com/forcewake/forge && cd forge\n"
        "uv sync && set -o pipefail && .venv/bin/python -m pytest -q\n"
        "```"
    )


# ---------------------------------------------------------------------------
# Targets: where the blocks live, and how to find them the FIRST time (the
# legacy hand-edited pins this script replaces).
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _Spot:
    """One pin location in one file.

    ``legacy`` matches the hand-edited span this script takes over on its
    first run; ``signature`` matches the rendered block's body so the RIGHT
    fenced span is replaced when a file carries several blocks.
    """

    legacy: re.Pattern[str]
    signature: re.Pattern[str]


_STATUS_LEGACY = re.compile(
    r"\(`" + re.escape(_IMAGE_TAG) + r":[0-9][0-9.abrc]*`\)\.", re.MULTILINE
)
_QUICKSTART_LEGACY = re.compile(
    r"```bash\n[^\n]*\n[^\n]*" + re.escape(_IMAGE_TAG) + r":[0-9][0-9.abrc]*.*?```",
    re.DOTALL,
)

TARGETS: dict[str, dict[str, _Spot]] = {
    # docs/getting-started/*.md pin no versions today (verified 2026-09-23);
    # add a _Spot per file here when one starts to.
    "README.md": {
        "status": _Spot(legacy=_STATUS_LEGACY, signature=re.compile(r"verdict `")),
        "quickstart": _Spot(legacy=_QUICKSTART_LEGACY, signature=re.compile(r"docker run")),
    },
}

_FENCED = re.compile(re.escape(BEGIN) + r"\n(.*?)\n" + re.escape(END), re.DOTALL)


def _replace_or_insert(content: str, spot: _Spot, block: str, where: str) -> str:
    fenced = f"{BEGIN}\n{block}\n{END}"
    for match in _FENCED.finditer(content):
        if spot.signature.search(match.group(1)):
            return content[: match.start()] + fenced + content[match.end() :]
    match = spot.legacy.search(content)
    if match is None:
        raise PinsError(
            f"{where}: no generated pin block and no legacy pin to take over — "
            "add the block manually or fix the anchor"
        )
    return content[: match.start()] + fenced + content[match.end() :]


def generate(
    root: Path,
    files: dict[str, dict[str, _Spot]],
    record: _Record,
    evidence_rel: str,
    pending_version: str | None = None,
) -> dict[str, str]:
    """New content per file (unchanged files map to identical strings)."""
    rendered = {
        "status": lambda: render_status_block(record, evidence_rel),
        "quickstart": lambda: render_quickstart_block(record, pending_version),
    }
    updated: dict[str, str] = {}
    for relpath, spots in files.items():
        content = (root / relpath).read_text(encoding="utf-8")
        new = content
        for spot_id, spot in spots.items():
            if spot_id not in rendered:
                raise PinsError(f"unknown spot {spot_id!r}")
            new = _replace_or_insert(new, spot, rendered[spot_id](), f"{relpath}:{spot_id}")
        updated[relpath] = new
    return updated


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the target files match the generated content; exit 1 on drift",
    )
    args = parser.parse_args(argv)

    record, record_path = latest_record(args.root)
    evidence_rel = record_path.relative_to(args.root).as_posix()
    tree_version = current_version(args.root)
    pending_version: str | None = None
    if tree_version and _version_key(tree_version) > _version_key(record.version):
        pending_version = tree_version
    try:
        updated = generate(args.root, TARGETS, record, evidence_rel, pending_version)
    except PinsError as exc:
        print(f"generate-template-pins: REFUSED: {exc}", file=sys.stderr)
        return 2

    drifted = False
    for relpath, new in sorted(updated.items()):
        path = args.root / relpath
        current = path.read_text(encoding="utf-8")
        if current == new:
            print(f"generate-template-pins: {relpath} in sync (v{record.version})")
            continue
        drifted = True
        if args.check:
            print(
                f"generate-template-pins: DRIFT — {relpath} does not match the pins "
                f"generated from {evidence_rel}; run "
                f"`python3 scripts/generate_template_pins.py` and commit",
                file=sys.stderr,
            )
        else:
            path.write_text(new, encoding="utf-8")
            print(f"generate-template-pins: rewrote {relpath} (v{record.version})")

    if args.check and drifted:
        return 1
    window = (
        f" — pre-release window: quick-start pulls v{pending_version} (digest pending promotion)"
        if pending_version
        else ""
    )
    print(
        f"generate-template-pins: pins render v{record.version} "
        f"({_verdict_line(record)}) from {evidence_rel}{window}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
